import { IInventoryItem } from "@/types/model";

export const MoneyDetail = [
  {
    label: "1,000",
    denom: "1000.00",
    imgURL: "/assets/images/1000THB-17th-Banknote-Front.jpg",
    inStacker: 0,
    qty: 0,
    value: 1000,
    statusStacker: 22,
    statusCassette: 22,
  },
  {
    label: "500",
    denom: "500.00",
    imgURL: "/assets/images/500THB-17th-Banknote-Front.jpg",
    inStacker: 0,
    qty: 0,
    value: 500,
    statusStacker: 22,
    statusCassette: 22,
  },
  {
    label: "100",
    denom: "100.00",
    imgURL: "/assets/images/100THB-17th-Banknote-Front.jpeg",
    inStacker: 0,
    qty: 0,
    value: 100,
    statusStacker: 22,
    statusCassette: 22,
  },
  {
    label: "50",
    denom: "50.00",
    imgURL: "/assets/images/50THB-17th-Banknote-Front.jpg",
    inStacker: 0,
    qty: 0,
    value: 50,
    statusStacker: 22,
    statusCassette: 22,
  },
  {
    label: "20",
    denom: "20.00",
    imgURL: "/assets/images/20THB-17th-Banknote-Front.jpg",
    inStacker: 0,
    qty: 0,
    value: 20,
    statusStacker: 22,
    statusCassette: 22,
  },
  {
    label: "10",
    denom: "10.00",
    imgURL: "/assets/images/10.png",
    inStacker: 0,
    qty: 0,
    value: 10,
    statusStacker: 22,
    statusCassette: 22,
  },
  {
    label: "5",
    denom: "5.00",
    imgURL: "/assets/images/5.png",
    inStacker: 0,
    qty: 0,
    value: 5,
    statusStacker: 22,
    statusCassette: 22,
  },
  {
    label: "2",
    denom: "2.00",
    imgURL: "/assets/images/2 Coin.png",
    inStacker: 0,
    qty: 0,
    value: 2,
    statusStacker: 22,
    statusCassette: 22,
  },
  {
    label: "1",
    denom: "1.00",
    imgURL: "/assets/images/1 Coin.png",
    inStacker: 0,
    qty: 0,
    value: 1,
    statusStacker: 22,
    statusCassette: 22,
  },
  {
    label: "0.50",
    denom: "0.50",
    imgURL: "/assets/images/0.5 Coin.png",
    inStacker: 0,
    qty: 0,
    value: 0.5,
    statusStacker: 22,
    statusCassette: 22,
  },
  {
    label: "0.25",
    denom: "0.25",
    imgURL: "/assets/images/0.25 Coin.png",
    inStacker: 0,
    qty: 0,
    value: 0.25,
    statusStacker: 22,
    statusCassette: 22,
  },
] as IInventoryItem[];
