import { INavbarItem } from "@/types/share";

export const ADMIN_HOME_MENUS = [
  {
    key: "replenishment",
    imgURL: "/assets/icons/archive-restore.svg",
    route: "/admin/replenish",
    en: "Replenish",
    th: "เติมเงินทอน",
    permission: "CASH_REPLENISH",
    disable: false,
    adminMain: true,
  },
  {
    key: "deposit",
    imgURL: "/assets/icons/package.svg",
    en: "Deposit",
    route: "/admin/deposit",
    th: "ฝากยอดขาย",
    permission: "CASH_REPLENISH",
    disable: false,
    adminMain: true,
  },
  {
    key: "withdraw",
    imgURL: "/assets/icons/hand-coins.svg",
    en: "Withdraw cash",
    route: "/admin/withdraw",
    th: "ถอนเงิน",
    permission: "CASH_DISPENSE",
    disable: false,
    adminMain: true,
  },
  {
    key: "exchangecash",
    imgURL: "/assets/icons/badge-dollar-sign.svg",
    en: "Exchange cash",
    route: "/admin/exchange",
    th: "แลกเงิน",
    permission: "CASH_EXCHANGE",
    disable: false,
    adminMain: true,
  },
  {
    key: "remove-cassete",
    imgURL: "/assets/icons/calendar-payment-loan.svg",
    route: "/admin/remove-cassete",
    en: "Remove Cassete",
    th: "นำเงินออกระหว่างวัน",
    permission: "UNLOCK_CASSETTE",
    disable: false,
    adminMain: true,
  },
  {
    key: "endofday",
    imgURL: "/assets/icons/calendar-clock.svg",
    route: "/admin/endofday",
    en: "End of day",
    th: "ปิดวันสิ้น",
    permission: "UNLOCK_CASSETTE",
    disable: false,
    adminMain: true,
  },

  {
    key: "checkdiff",
    imgURL: "/assets/icons/calendar-clock.svg",
    route: "/admin/check-diff",
    en: "check-dif",
    th: "ตรวจสอบรายการ",
    permission: "BACK_OFFICE",
    disable: false,
    adminMain: false,
    isDanger: true,
  },
  {
    key: "user",
    imgURL: "/assets/icons/user.svg",
    route: "/admin/user",
    en: "User",
    th: "จัดการผู้ใช้",
    permission: "MANAGE_USER",
    disable: false,
    adminMain: false,
    isDanger: true,
  },
  {
    key: "reset",
    imgURL: "/assets/icons/rotate-ccw.svg",
    route: "/admin/reset",
    en: "reset",
    th: "รีเซ็ตเครื่อง",
    permission: "BACK_OFFICE",
    disable: false,
    adminMain: false,
    isDanger: true,
  },
  {
    key: "backhome",
    imgURL: "/assets/icons/rotate-ccw.svg",
    route: "/",
    en: "backhome",
    th: "กลับหน้าหลัก",
    permission: "BACK_OFFICE",
    disable: false,
    adminMain: false,
    isDanger: true,
  },
] as INavbarItem[];

export const ADMIN_NAVBAR_CI = [
  {
    key: "Admin",
    imgURL: "/assets/icons/user.svg",
    route: "/admin",
    en: "Admin",
    th: "แอดมิน",
    disable: false,
  },
  {
    key: "Inventory",
    imgURL: "/assets/icons/layout-dashboard.svg",
    route: "/inventory",
    en: "Inventory",
    th: "คอเล็คชั่น",
    disable: false,
  },
  {
    key: "Transactions",
    imgURL: "/assets/icons/layout-dashboard.svg",
    route: "/transactions",
    en: "Transactions",
    th: "ทรานซิสชั่น",
    disable: true,
  },
  {
    key: "Report",
    imgURL: "/assets/icons/file-bar-chart.svg",
    route: "/report",
    en: "Report",
    th: "รายงาน",
    disable: false,
  },
] as INavbarItem[];
